apiVersion: v1
kind: Secret
metadata:
  name: gestion-financiera-secrets

type: Opaque

stringData:
  DB_URL: "<CAMBIAR>"
  DB_USERNAME: "<CAMBIAR>"
  DB_PASSWORD: "<CAMBIAR>"
  JWT_SECRET: "<CAMBIAR>"